### ISSUE TITLE
انتشار دیتابیس

### ISSUE THREAD

**Issue by zoghal** [RaminNietzsche/jobguy#2]
درود بر شما
از اتفاقی که افتاده متاسفم، اما بهترن نبود دیتابیس رو منتشر می‌کردید!
حداقل بصورت فیلتر شده و ناقص!

**Comment by ohmydevops** [comment]
<div dir='rtl'>
فکر میکنم اشتباه برداشت کردین. این دوستان وبسایت جاب‌گای رو اسکرپ کردن و نتایجش رو اینجا قرار دادند. بنیانگذار جاب‌گای نیستند که به دیتابیس دسترسی داشته باشند.
</div>

**Comment by zoghal** [comment]
آره اشتباه متوجه شدم.
ممنون :)
